require 'lua/plug-config/lualine'
require 'lua/plug-config/tabline'
require 'lua/plug-config/devicons'
require 'lua/plug-config/cmp'
require 'lua/plug-config/presence'
require 'lua/plug-config/telescope'
require 'lua/plug-config/nvim-tree'
