require 'lua/plug-config/lualine/lualine'
require 'lua/plug-config/tabline/tabline'
require 'lua/plug-config/devicons/devicons'
require 'lua/plug-config/cmp/cmp'
require 'lua/plug-config/presence/presence'
require 'lua/plug-config/telescope/telescope'
require 'lua/plug-config/nvim-tree/nvim-tree'
